# Documentação do Pandas
https://pandas.pydata.org/pandas-docs/stable/index.html

### Importando biblioteca e lendo o dataset

In [1]:
import pandas as pd

In [2]:
#leitura do dataset no meu drive
#df = pd.read_csv('fake_data_2.csv')

In [3]:
#OU coloca direto o endereço do csv (nesse caso, nem precisaria montar o drive)
df = pd.read_csv('https://raw.githubusercontent.com/CaiqueCoelho/Preprocessing-Dataset-Template/master/fake_data_2.csv')

In [4]:
df

          cargo  idade  salario    bonus sócio
0       Diretor     45  24000.0  10000.0   sim
1      Analista     22   8000.0   2000.0   não
2   Programador     30      NaN   1000.0   não
3       Gerente     24  15100.0      NaN   não
4       Gerente     30  35000.0   6000.0   sim
5   Programador     22   5300.0   2000.0   não
6      Analista     20      NaN   1200.0   não
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

# 2 - Visão geral do dataset

### Trabalhando com dataframes

In [5]:
df.head(3)

         cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não

In [7]:
df.tail()

          cargo  idade  salario    bonus sócio
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

In [8]:
#Apresenta as colunas do dataset
df.columns

Index(['cargo', 'idade', 'salario', 'bonus', 'sócio'], dtype='str')

In [9]:
#Fazendo referência a uma coluna especifica
df['salario']

0     24000.0
1      8000.0
2         NaN
3     15100.0
4     35000.0
5      5300.0
6         NaN
7     18000.0
8     38000.0
9      7300.0
10     2344.0
11     4500.0
12    30000.0
13    14000.0
Name: salario, dtype: float64

In [10]:
#Mostrando as linhas de 0 a 3
df[0:4]

         cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não

In [11]:
#Fazendo referência a algumas colunas
df[['cargo', 'idade']] #dois colchetes nesse caso

          cargo  idade
0       Diretor     45
1      Analista     22
2   Programador     30
3       Gerente     24
4       Gerente     30
5   Programador     22
6      Analista     20
7       Diretor     50
8      Fundador     65
9      Analista     32
10  Programador     35
11  Programador     28
12     Fundador     28
13  Programador     30

In [12]:
#Apresenta os valores unicos da coluna selecionada
df['cargo'].unique()

<StringArray>
['Diretor', 'Analista', 'Programador', 'Gerente', 'Fundador']
Length: 5, dtype: str

In [13]:
#Renomeando colunas
df.rename(columns={'sócio':'socio'})

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
1      Analista     22   8000.0   2000.0   não
2   Programador     30      NaN   1000.0   não
3       Gerente     24  15100.0      NaN   não
4       Gerente     30  35000.0   6000.0   sim
5   Programador     22   5300.0   2000.0   não
6      Analista     20      NaN   1200.0   não
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

In [14]:
#A operação do rename não alterou o banco original. Nesse caso precisariamos guardar o resultado da operação em outra variável
df.head()

         cargo  idade  salario    bonus sócio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não
4      Gerente     30  35000.0   6000.0   sim

In [15]:
#Para que a alteração seja realizada no dataframe original, precisamos o parâmetro inplace
df.rename(columns={'sócio':'socio'}, inplace = True)
df.head()

         cargo  idade  salario    bonus socio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não
4      Gerente     30  35000.0   6000.0   sim

In [16]:
#Verifica os tipos e valores faltosos
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   cargo    14 non-null     str
 1   idade    14 non-null     int64
 2   salario  12 non-null     float64
 3   bonus    12 non-null     float64
 4   socio    14 non-null     str
dtypes: float64(2), int64(1), str(2)
memory usage: 692.0 bytes

In [17]:
#Verifica os valores faltosos
df.isna()

    cargo  idade  salario  bonus  socio
0   False  False    False  False  False
1   False  False    False  False  False
2   False  False     True  False  False
3   False  False    False   True  False
4   False  False    False  False  False
5   False  False    False  False  False
6   False  False     True  False  False
7   False  False    False  False  False
8   False  False    False  False  False
9   False  False    False  False  False
10  False  False    False   True  False
11  False  False    False  False  False
12  False  False    False  False  False
13  False  False    False  False  False

In [18]:
#Sumariza os valores faltosos por coluna/atributo
df.isna().sum()

cargo      0
idade      0
salario    2
bonus      2
socio      0
dtype: int64

In [19]:
#Verifica informações gerais sobre colunas numéricas
df.describe()

           idade       salario         bonus
count  14.000000     12.000000     12.000000
mean   32.928571  16795.333333   7200.000000
std    12.499011  12355.108162   7610.996829
min    20.000000   2344.000000   1000.000000
25%    25.000000   6800.000000   2000.000000
50%    30.000000  14550.000000   5000.000000
75%    34.250000  25500.000000  10000.000000
max    65.000000  38000.000000  28000.000000

**loc**

Pode-se usar o método loc para localizar linhas ou pedaços do dataframe pelos rótulos

Sintaxe:

loc[linhas, colunas]

Onde as linhas e colunas podem ser passadas em sequencia (:) ou saltos (,)

In [20]:
df.loc[0, 'cargo'] #Um elemento

'Diretor'

In [21]:
df.loc[0:3] #Uma sequência de linhas

         cargo  idade  salario    bonus socio
0      Diretor     45  24000.0  10000.0   sim
1     Analista     22   8000.0   2000.0   não
2  Programador     30      NaN   1000.0   não
3      Gerente     24  15100.0      NaN   não

In [22]:
df.loc[0:3, 'cargo':'salario'] #pedaço do dataframe, usando sequencia de linhas e colunas

         cargo  idade  salario
0      Diretor     45  24000.0
1     Analista     22   8000.0
2  Programador     30      NaN
3      Gerente     24  15100.0

In [23]:
df.loc[[0,3], ['cargo', 'salario']] #pedaço do dataframe, usando linhas e colunas em saltos (observar colchetes)

     cargo  salario
0  Diretor  24000.0
3  Gerente  15100.0

In [24]:
#Como pegar duas sequências diferentes:

pd.concat([df.loc[0:3], df.loc[10:12]])

#Pode usar o concat do pandas que irá concatenar dois dataframes (ou pedaços de dataframes)

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
1      Analista     22   8000.0   2000.0   não
2   Programador     30      NaN   1000.0   não
3       Gerente     24  15100.0      NaN   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim

**iloc**

Pode-se usar o método iloc para localizar linhas ou pedaços do dataframe pelos índices numéricos (posicionais)

Sintaxe (igual a do loc):

iloc[linhas, colunas]

Onde as linhas e colunas podem usar sequencias (:) ou saltos (,)

A diferença de iloc para loc é que loc usa os rotulos, enquanto iloc usa os indices numericos default

In [25]:
df.iloc[0, 0] #um elemento (linha 0, coluna cargo)

'Diretor'

In [26]:
df.iloc[0:3, 0:3] #sequencia

         cargo  idade  salario
0      Diretor     45  24000.0
1     Analista     22   8000.0
2  Programador     30      NaN

In [27]:
df.iloc[[0,3], [0,3]] #salto

     cargo    bonus
0  Diretor  10000.0
3  Gerente      NaN

## Filtros no Data Frame

#### 1 - Diretamente nas colunas

In [28]:
df['idade']>25

0      True
1     False
2      True
3     False
4      True
5     False
6     False
7      True
8      True
9      True
10     True
11     True
12     True
13     True
Name: idade, dtype: bool

In [29]:
#Filtrando valores em uma coluna especifica
df[df['idade']>25]

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
2   Programador     30      NaN   1000.0   não
4       Gerente     30  35000.0   6000.0   sim
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

In [30]:
#Guardando o resultado do filtro em outra variavel
df_idade = df[df['idade']>25]
print(df_idade)

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
2   Programador     30      NaN   1000.0   não
4       Gerente     30  35000.0   6000.0   sim
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

In [31]:
#Apresentando o formato da variavel
df_idade.shape

(10, 5)

In [32]:
(df['idade']>25) & (df['salario']>7000)

0      True
1     False
2     False
3     False
4      True
5     False
6     False
7      True
8      True
9      True
10    False
11    False
12     True
13     True
dtype: bool

In [33]:
df[(df['idade']>25) & (df['salario']>7000)]

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
4       Gerente     30  35000.0   6000.0   sim
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

#### 2 - Usando o método query

In [34]:
#Outra forma de filtrar dados no Dataset é por meio do método query
df.query('idade >25')

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
2   Programador     30      NaN   1000.0   não
4       Gerente     30  35000.0   6000.0   sim
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

In [35]:
df.query('idade >25 & salario>7000')

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
4       Gerente     30  35000.0   6000.0   sim
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
12     Fundador     28  30000.0  12000.0   sim
13  Programador     30  14000.0  10000.0   sim

In [36]:
#Usando uma variavel como parametro na query
idade_mediana = df['idade'].median()
print(idade_mediana)

30.0

In [37]:
df.query('idade>@idade_mediana')

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
7       Diretor     50  18000.0   8000.0   sim
8      Fundador     65  38000.0  28000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não

In [38]:
#Query com string
df.query('cargo == "Diretor"')

     cargo  idade  salario    bonus socio
0  Diretor     45  24000.0  10000.0   sim
7  Diretor     50  18000.0   8000.0   sim

In [39]:
#O metodo isin seleciona os registros que atendem aos itens listados
df[df['cargo'].isin(['Analista','Programador','Diretor'])]

          cargo  idade  salario    bonus socio
0       Diretor     45  24000.0  10000.0   sim
1      Analista     22   8000.0   2000.0   não
2   Programador     30      NaN   1000.0   não
5   Programador     22   5300.0   2000.0   não
6      Analista     20      NaN   1200.0   não
7       Diretor     50  18000.0   8000.0   sim
9      Analista     32   7300.0   4000.0   não
10  Programador     35   2344.0      NaN   não
11  Programador     28   4500.0   2200.0   não
13  Programador     30  14000.0  10000.0   sim

#### 3 - Utilizando o método filter

In [40]:
df.filter(['cargo','idade','salario'])

          cargo  idade  salario
0       Diretor     45  24000.0
1      Analista     22   8000.0
2   Programador     30      NaN
3       Gerente     24  15100.0
4       Gerente     30  35000.0
5   Programador     22   5300.0
6      Analista     20      NaN
7       Diretor     50  18000.0
8      Fundador     65  38000.0
9      Analista     32   7300.0
10  Programador     35   2344.0
11  Programador     28   4500.0
12     Fundador     28  30000.0
13  Programador     30  14000.0

### Métodos úteis
Value_counts

retorna uma série contendo contagens de valores únicos. O objeto resultante estará em ordem decrescente para que o primeiro elemento seja o elemento que ocorre com mais frequência. Exclui valores NA por padrão.

In [41]:
#Apresenta a quantidade de valores unicos para uma coluna em particular
df['socio'].value_counts()

socio
não    8
sim    6
Name: count, dtype: int64

In [42]:
#apresenta a quantidade de valores em cada coluna
df.count()

cargo      14
idade      14
salario    12
bonus      12
socio      14
dtype: int64

In [43]:
df['cargo'].count()

np.int64(14)

Groupby

In [44]:
obj = df.groupby('cargo')
obj

In [45]:
obj.groups

{'Analista': [1, 6, 9], 'Diretor': [0, 7], 'Fundador': [8, 12], 'Gerente': [3, 4], 'Programador': [2, 5, 10, 11, 13]}

In [46]:
df.groupby('cargo').count()

             idade  salario  bonus  socio
cargo
Analista         3        2      3      3
Diretor          2        2      2      2
Fundador         2        2      2      2
Gerente          2        2      1      2
Programador      5        4      4      5

In [47]:
#Experimente usar count
df.groupby('cargo')['idade'].count()

cargo
Analista       3
Diretor        2
Fundador       2
Gerente        2
Programador    5
Name: idade, dtype: int64

In [48]:
#Experimente calcular a media e a mediana do agrupamemto
df.groupby('cargo')['salario'].sum()

cargo
Analista       15300.0
Diretor        42000.0
Fundador       68000.0
Gerente        50100.0
Programador    26144.0
Name: salario, dtype: float64

#### AGREGANDO INFORMAÇÕES NO GROUPBY

In [49]:
import numpy as np

In [50]:
obj2 = df.groupby('cargo')[['idade','salario','bonus']]

In [51]:
obj2.agg([np.mean,np.median])

                 idade         salario             bonus
                  mean median     mean   median     mean   median
cargo
Analista     24.666667   22.0   7650.0      NaN   2400.0   2000.0
Diretor      47.500000   47.5  21000.0  21000.0   9000.0   9000.0
Fundador     46.500000   46.5  34000.0  34000.0  20000.0  20000.0
Gerente      27.000000   27.0  25050.0  25050.0   6000.0      NaN
Programador  29.000000   30.0   6536.0      NaN   3800.0      NaN

In [52]:
obj2.mean().sort_values(by='salario',ascending=True)

                 idade  salario    bonus
cargo
Programador  29.000000   6536.0   3800.0
Analista     24.666667   7650.0   2400.0
Diretor      47.500000  21000.0   9000.0
Gerente      27.000000  25050.0   6000.0
Fundador     46.500000  34000.0  20000.0

In [53]:
df.groupby(['cargo','socio']).count()

                   idade  salario  bonus
cargo       socio
Analista    não        3        2      3
Diretor     sim        2        2      2
Fundador    sim        2        2      2
Gerente     não        1        1      0
            sim        1        1      1
Programador não        4        3      3
            sim        1        1      1

In [54]:
df.groupby(['cargo','socio']).agg(media_salario =('salario',np.mean),mediana_idade=('idade',np.median))

                   media_salario  mediana_idade
cargo       socio
Analista    não           7650.0           22.0
Diretor     sim          21000.0           47.5
Fundador    sim          34000.0           46.5
Gerente     não          15100.0           24.0
            sim          35000.0           30.0
Programador não           4048.0           29.0
            sim          14000.0           30.0

In [55]:
#Estatística básica da idade de cada cargo
df.groupby('cargo')['idade'].describe()

             count       mean        std   min    25%   50%    75%   max
cargo
Analista       3.0  24.666667   6.429101  20.0  21.00  22.0  27.00  32.0
Diretor        2.0  47.500000   3.535534  45.0  46.25  47.5  48.75  50.0
Fundador       2.0  46.500000  26.162951  28.0  37.25  46.5  55.75  65.0
Gerente        2.0  27.000000   4.242641  24.0  25.50  27.0  28.50  30.0
Programador    5.0  29.000000   4.690416  22.0  28.00  30.0  30.00  35.0